### ISSUE TITLE
查询错乱

### ISSUE THREAD

**Issue by ghost** [hundunzhidian/RconA2sAPi#1]
- 查询出服务器信息结果错乱 ![](https://i.imgur.com/Ze8tDMh.png)

**Comment by hundunzhidian** [comment]
可能由于java的byte类型数据是从-127~128的原因，请打开服务器，我拿一下原始数据包

**Comment by ghost** [comment]
还有 命令也不行 connect timed out

**Comment by ghost** [comment]
@hundunzhidian 服务器  47.102.45.140:6888

**Comment by ghost** [comment]
@hundunzhidian 管理密码 test  测试玩我再修改

**Comment by hundunzhidian** [comment]
服务器的防火墙开了吗，rcon命令需要开启tcp，并且设置好rcon密码，同时服务器启动的时候必须指定内网的ip

**Comment by ghost** [comment]
@hundunzhidian  开了 也是内网

**Comment by hundunzhidian** [comment]
已确认，服务器为cs，属于Obsolete GoldSource通信协议，跟现在l4d2以及csgo的协议有几个字段不一致，等我这俩天发布升级

**Comment by ghost** [comment]
@hundunzhidian rcon 命令 除了指定ip还需要注意些什么比如ipx？

**Comment by hundunzhidian** [comment]
hlsw能测试成功，估摸着还是我的api只支持最新的协议，等我分析一下老引擎的rcon协议，rcon协议比较复杂

**Comment by ghost** [comment]
@hundunzhidian 顺便加上判断服务器是否加密
:smile:

**Comment by hundunzhidian** [comment]
功能已经做好，稍后发布更新，请启动服务器，我测试下rcon命令功能

**Comment by hundunzhidian** [comment]
已发布升级，可以下载最新的release包，加入了对起源老引擎的支持，以及服务器是否需要密码进入

**Comment by ghost** [comment]
@hundunzhidian rcon 命令还是不行

**Comment by hundunzhidian** [comment]
抓包分析过了，老引擎不支持tcp的rcon协议，仅支持udp的rcon通信协议，这俩天更新下

**Comment by hundunzhidian** [comment]
已发布更新，注意查看，测试了基本没问题了，老起源的rcon命令比较特殊，有的可能没有返回值

**Comment by ghost** [comment]
@hundunzhidian  密码无效![](https://i.imgur.com/3Nu451x.png)
