### ISSUE TITLE
Error in spelling

### ISSUE THREAD

**Issue by Antonio112009** [hundunzhidian/RconA2sAPi#2]
I found error in `/players` command JSON respond:

You typed "socre" everywhere instead of "score"

![image](https://user-images.githubusercontent.com/29264726/81477975-70ef0280-9212-11ea-8b4a-330a54732a87.png)

Needs to be:

![image](https://user-images.githubusercontent.com/29264726/81477956-587ee800-9212-11ea-8f94-eae0c724fbbe.png)

**Comment by hundunzhidian** [comment]
sorry for that,this is my mistake. Now fixed
